# Generated by Django 6.1 on 2026-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_pedido_pedidoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='criado_em',
            new_name='data',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
