# Generated by Django 6.1 on 2026-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_rename_criado_em_pedido_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
